from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')
path = [cwd]
path += [cwd + '/Inc']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
